apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-service
          command: [
            "/k8s-service",
            "--server_address=0.0.0.0:8080",
            "--selector=static"
          ]
          image: k8s-service:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            name: user-port